### ISSUE TITLE
The hero section have incorrect route

### ISSUE THREAD

**Issue by Simply007** [alanta/kontent-statiq-theme-planty#1]
I suppose the `See all plants` button should lead to `/store` route instead of `/shop`

![image](https://user-images.githubusercontent.com/9218736/106509450-f071df80-64cd-11eb-9301-5f3d5990af7e.png)

Output:
* https://github.com/alanta/kontent-statiq-theme-planty/blob/77f625acc0b63b3e6e89103c22ca9eff0cab4f76/index.html#L97

Can't fix the issue, because I haven't found the referenced `content.zip` [referenced in readme](https://github.com/alanta/kontent-statiq-theme-planty#create-a-content-source)

**Comment by alanta** [comment]
Doh, thanks for pointing this out. I've updated the link and added content.zip to the repo.
